### ISSUE TITLE
not normalized counts when saving results tables from DE

### ISSUE THREAD

**Issue by mistrm82** [hbc/bcbioRNASeq#111]
After running `resultsTables()` followed by `saveData()` the final results files have columns that correspond to normalized count values for each sample. When I cross-reference with the normalized counts data matrix it doesn't match up. The question is what are these values that are being reported?

**Comment by roryk** [comment]
Sorry for the problem, Meeta. It looks like these should be pulling in the normalized counts https://github.com/hbc/bcbioRNASeq/blob/master/R/methods-resultsTables.R#L219 for DESeq2 results objects. Do you think you could pass on the DESeqResults and DESeqDataSet objects that are going into this call so I can see if I can reproduce and fix it? Thanks!

**Comment by mistrm82** [comment]
Thanks @roryk !

**Comment by mjsteinbaugh** [comment]
Are we able to reproduce this error? I can look into it this weekend.

**Comment by roryk** [comment]
Haven't had a chance to look at it yet, I stuck up a ZIP file of the data Meeta sent here:

[res.zip](https://github.com/hbc/bcbioRNASeq/files/2297423/res.zip)

**Comment by mjsteinbaugh** [comment]
Do we have the corresponding dds and/or bcb objects? That seems to be the potential issue is that there could be a mismatch

**Comment by roryk** [comment]
[resdds.zip](https://github.com/hbc/bcbioRNASeq/files/2298161/resdds.zip)
Oop.

**Comment by mjsteinbaugh** [comment]
Thanks Rory I'll take a look

**Comment by mjsteinbaugh** [comment]
I've been working on an improved approach for handling the `DESeqResults` tables and optionally including the normalized counts from the `DESeqDataSet`, which is documented here: 

https://github.com/hbc/bcbioRNASeq/blob/develop/R/DESeqResultsTables-methods.R

Also of interest, you can return `DESeqResults` as a `GRanges` instead of a `DataFrame`, which will include the genome annotations.
