### ISSUE TITLE
stopifnot(is(res, "DESeqResults"))

### ISSUE THREAD

**Issue by jxshi** [hbc/bcbioRNASeq#118]
Hi, guys,

I encountered the following error message when I was using bcbioRNASeq tools to do function annotation for differential expression analysis. This is the parameter that I designated in params ```  res_file: "data/2018-11-12/res_list_shrunken.rda"```. When I checked previous results, I noticed that this parameter was ```  res_file: "data/YYYY-MM-DD/res.rda" ```. 
```
Error in eval(expr, envir, enclos) : is(res, "DESeqResults") is not TRUE
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> stopifnot
Execution halted
```
I have tried all the output from Differential Expression step, they all resulted the above error message.
Can you guys check for me please?  TIA!

Best,

Jianxiang

**Comment by mjsteinbaugh** [comment]
Hi @jxshi, the discrepancy here is that I updated our differential expression template to be parameterized and it now supports multiple contrasts, returning a list of `DESeqResults` (e.g. `res_list_shrunken`). The functional analysis template isn't fully parameterized yet to work with multiple contrasts.

To run the functional analysis, simply pull the individual `DESeqResults` object you want out of the list and save it to disk. Then you can refer to that in the `res_file` argument. I'm working on an improved GSEA template that uses the fgsea package instead of clusterProfiler, which will be available in the upcoming v0.3.0 release. It will be based off of this guide with some modifications: [DESeq to FGSEA](https://stephenturner.github.io/deseq-to-fgsea/).

Best,
Mike
