### ISSUE TITLE
bcbioRNAseq encountered problem in KEGG analysis when processing data from Rattus norvegicus

### ISSUE THREAD

**Issue by jxshi** [hbc/bcbioRNASeq#143]
Hi,

I was using ```bcbioRNAseq``` to analyze data from ```Rattus norvegicus```. The ```functional annotation``` step encountered error when performing ```KEGG``` analysis.

Here is the command it got stuck:
```
## Define the Ensembl gene to Entrez identifier mappings.
gene2entrez <- rowData(dds)$entrezID
stopifnot(
    is.list(gene2entrez),
    !is.null(names(gene2entrez))
)
```
I have checked ```rowData(dds)$entrezID```, it returned ```null```. I checked further and found that there was no ```entrezID``` column in ```rowData(dds)```. 

I also have data from ```Homo sapiens```, there was no such problem.

Can you check for me please?

Merry Christmas and Happy New Year!

Jianxiang

**Comment by mjsteinbaugh** [comment]
Hi @jxshi, sorry for the slow response, I was on vacation at the end of December and had to work through a backlog of issues.

Regarding KEGG analysis for *Rattus norvegicus*, you should be able to run it but it looks like you'll have to modify your DESeqDataSet object first.

Here's how to get the required Ensembl-to-Entrez gene identifier mappings from AnnotationHub, using my basejump package.

```r
library(basejump)
rn <- makeGRangesFromEnsembl(organism = "Rattus norvegicus")
names(mcols(rn))
```

```
[1] "broadClass"     "description"    "entrezID"       "geneBiotype"
[5] "geneID"         "geneIDVersion"  "geneName"       "seqCoordSystem"
```

```r
head(rn$entrezID)
```

```
$ENSRNOG00000000001
[1] NA

$ENSRNOG00000000007
[1] 24379

$ENSRNOG00000000008
[1] 296511

$ENSRNOG00000000009
[1] 366158

$ENSRNOG00000000010
[1] 498922

$ENSRNOG00000000012
[1] 296272
```

```r
genes <- rownames(dds)
stopifnot(all(genes %in% names(rn)))
rn <- rn[genes]
map <- Ensembl2Entrez(rn, format = "1:1")
rowData(dds)$entrezID <- map$entrezID
```

Let me know if that helps, otherwise I may need a copy of the `DESeqDataSet` you're using to run the template.

Best,
Mike

**Comment by jxshi** [comment]
Thanks a lot! That helps!
