### ISSUE TITLE
Error while running DE analysis

### ISSUE THREAD

**Issue by kokyriakidis** [hbc/bcbioRNASeq#166]
Hey @mjsteinbaugh 

I am getting an error when I try to run:
```
dds <- DESeq(dds)
```
I get the following:
```
> dds <- DESeq(dds)
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.
final dispersion estimates
fitting model and testing

warning: solve(): system seems singular; attempting approx solution
Error in fitBeta(ySEXP = ySEXP, xSEXP = xSEXP, nfSEXP = nfSEXP, alpha_hatSEXP = alpha_hatSEXP,  : 
  BLAS/LAPACK routine 'DGELSD' gave error code -4


## The traceback gives this

5. | fitBeta(ySEXP = ySEXP, xSEXP = xSEXP, nfSEXP = nfSEXP, alpha_hatSEXP = alpha_hatSEXP, contrastSEXP = contrastSEXP, beta_matSEXP = beta_matSEXP, lambdaSEXP = lambdaSEXP, weightsSEXP = weightsSEXP, useWeightsSEXP = useWeightsSEXP, tolSEXP = tolSEXP, maxitSEXP = maxitSEXP, useQRSEXP = useQRSEXP, ...
-- | --
4.
fitBetaWrapper(ySEXP = counts(object), xSEXP = modelMatrix, nfSEXP = normalizationFactors, alpha_hatSEXP = alpha_hat, beta_matSEXP = beta_mat, lambdaSEXP = lambdaNatLogScale, weightsSEXP = weights, useWeightsSEXP = useWeights, tolSEXP = betaTol, maxitSEXP = maxit, useQRSEXP = useQR, minmuSEXP = minmu)
3.
fitNbinomGLMs(objectNZ, betaTol = betaTol, maxit = maxit, useOptim = useOptim, useQR = useQR, renameCols = renameCols, modelMatrix = modelMatrix, minmu = minmu)
2.
nbinomWaldTest(object, betaPrior = betaPrior, quiet = quiet, modelMatrix = modelMatrix, modelMatrixType = modelMatrixType, useT = useT, minmu = minmu)
1.
DESeq(dds)


```

Do you have any clue about the isssue? I am trying to run an analysis with the following parameters
```
  design: !r formula("~ diseaseStatusFollowup")
  contrasts: !r list(c(factor ="diseaseStatusFollowup", numerator = "Stable", denominator = "PR"))

design(dds) <- params$design

```

The analysis was done with bcbio. You can acces the DESeqDataSet object in the following link:

```
https://drive.google.com/drive/folders/1XykjaX_lUa3G3VROrBrv5jvVs0WK6lwS?usp=sharing
```

Edit:
When I try to manually load object to DESeq2 I get the following error:
```
library("DESeq2")
ddsSE <- DESeqDataSet(object, design = ~ diseaseStatusFollowup)
ddsSE

Error in DESeqDataSet(object, design = ~"diseaseStatusFollowup") : some values in assay are not integers
```

Bcbio produces a new SumamrizedExperiment file when you run the analysis, that works fine when I load it but produces the same error the I try to run the DE. The file is called ```bcbio-se``` in the google drive folder. I has integer counts in the essay.

Edit2:
When I load the final bcbio folder using bcbioRnaseq commands I get wrong counts.
I get this:
```
> object@assays@data@listData[["counts"]]
                         PATIENT100  PATIENT1056  PATIENT1059  PATIENT1062  PATIENT1076
ENSG00000000003 0.000000e+00 8.143388e-01 0.000000e+00 0.000000e+00 8.122114e-01
```
I should get this according to the tximport-counts.csv file in the final folder:
```

gene | PATIENT100 | PATIENT1056 | PATIENT1059 | PATIENT1062 | PATIENT1076
ENSG00000000003 | 0 | 1 | 0 | 0 | 1

```

The tximport-counts.csv file is inside the gdrive folder

Edit3:
When I load it with bcbioRNASeq it changed my column names. I get diseaseStatusFollowup instead of disease_status_followup

Edit4:
Tried to import a project from alst year which worked then and I get this error again:
```
── DESeq2 normalizations ──

→ `estimateSizeFactors()`
→ `DESeq()`
using pre-existing size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing

warning: solve(): system seems singular; attempting approx solution
! Skipping DESeq2 calculations.
BLAS/LAPACK routine 'DGELSD' gave error code -4
✓ bcbio RNA-seq run imported successfully.
```

**Comment by kokyriakidis** [comment]
The problem arises only on my Linux distro. It works just fine in my Macbook. Will investigate further.

**Comment by mjsteinbaugh** [comment]
@kokyriakidis OK walking through these points:

1. Regarding the DESeq2 error: This seems to me like it is due to a system dependency issue or R package not having been built correctly. What Linux distro is generating that error? This might be worth posting on the [Bioconductor support forum](https://support.bioconductor.org).

2. bcbio has added support for creating a `SummarizedExperiment` automatically, using the built-in [`bcbio2se.R`](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/scripts/R/bcbio2se.R) script. This differs from the approach used in the bcbioRNASeq R package slightly. The `SummarizedExperiment` generated by bcbio has the counts rounded into integers, whereas bcbioRNASeq does not do that automatically, since having that extra precision is useful for some downstream applications. Instead, the counts are rounded to integer when handing off to DESeq2 via `dds <- as(bcb, "DESeqDataSet")`. That internal code is [defined here](https://github.com/hbc/bcbioRNASeq/blob/v0.3.39/R/internal-DESeq2.R#L10) in bcbioRNASeq, for reference. Basically this is what happens when converting the `bcbioRNASeq` object into a `DESeqDataSet`:

```r
counts <- counts(se)
counts <- round(counts, digits = 0L)
mode(counts) <- "integer"
counts(se) <- counts
```

If you take a look at your counts in the `bcbioRNASeq` object, those will round to the same integers seen in the other `SummarizedExperiment`. It's a good point to consider that maybe for gene-level output we should just round the counts to integers and keep this simpler. @roryk thoughts on this?

3. Regarding the sample metadata, the bcbioRNASeq package currently uses the convention of renaming all sample metadata input columns into lowerCamelCase. I'm taking a look at seeing if we can relax this a bit in the code, and allow input of snake_case formatted metadata columns as well without hitting any issues.

Best,
Mike

**Comment by kokyriakidis** [comment]
@mjsteinbaugh Thanks for the detailed info!

I use Ubuntu 20.04. I will reinstall R and all packages and see what is going on.

Regarding the naming: They look better that way. No need to change it. 

I am having trouble producing the QC plots for all my samples (172). As you can imagine they look bad. Do you know a way to create some QC plots for big sample data?

Best,
Konstantinos

**Comment by mjsteinbaugh** [comment]
That's a really good point also regarding QC on datasets with a large number of samples. We've run into this at the HSPH core as well. Unfortunately, R Markdown currently doesn't work great with really large/tall plots, unless maybe we define our own custom CSS style for the HTML output. Alternatively, you can save the QC plots manually using `ggsave()` and scale them using the `width` and `height` arguments -- see if that works a little bit better than the R Markdown output.
