### ISSUE TITLE
error with plotDEGHeatmap

### ISSUE THREAD

**Issue by Xiaofei-git** [hbc/bcbioRnaseq#181]
Running through the case study, but got error with plotDEGHeatmap, https://github.com/hbc/bcbioRNASeq/issues/112. I think I already passed it in a DESeqTransform. Many thanks for any comments. 
```
> dds <- DESeq(dds)
> vst <- varianceStabilizingTransformation(dds)
> plotDEGHeatmap(results = res, counts = vst)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘plotDEGHeatmap’ for signature ‘"missing"’
> dds
class: DESeqDataSet 
dim: 51652 12 
metadata(11): caller countsFromAbundance ... sessionInfo version
assays(4): counts mu H cooks
rownames(51652): ENSMUSG00000000001 ENSMUSG00000000003 ... ENSMUSG00000114967 ENSMUSG00000114968
rowData names(37): geneId geneName ... deviance maxCooks
colnames(12): control_rep1 control_rep2 ... fa_day7_rep2 fa_day7_rep3
colData names(26): sampleName day ... xGc sizeFactor
> vst
class: DESeqTransform 
dim: 51652 12 
metadata(11): caller countsFromAbundance ... sessionInfo version
assays(1): ''
rownames(51652): ENSMUSG00000000001 ENSMUSG00000000003 ... ENSMUSG00000114967 ENSMUSG00000114968
rowData names(37): geneId geneName ... dispGeneIter dispFit
colnames(12): control_rep1 control_rep2 ... fa_day7_rep2 fa_day7_rep3
colData names(26): sampleName day ... xGc sizeFactor
```

**Comment by mjsteinbaugh** [comment]
Hi @Xiaofei-git , `plotDEGHeatmap()` is an S4 generic function defined in our [AcidGenerics](https://r.acidgenomics.com/packages/acidgenerics/) package, with method support for DESeq2 provided in our [DESeqAnalysis](https://r.acidgenomics.com/packages/deseqanalysis/) package. I'm closing this issue and referring to you the related issue above, which provides more detail.

Briefly, you're seeing this issue:

```
plotDEGHeatmap(results = res, counts = vst)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘plotDEGHeatmap’ for signature ‘"missing"’
```

because the `plotDEGHeatmap` generic function dispatches on `object` instead of `results` as the primary argument. Generics in R can be a bit cryptic about this mismatch error in R, and should say something like `use "object" instead of "results"` instead of returning `signature ‘"missing"’`. But I also recommend that you now create a `DESeqAnalysis` object as explained in the post and the updated bcbioRNASeq differential expression workflow, which makes usage of such visualization functions like `plotDEGHeatmap` more intuitive.

The example code in the F1000 case study paper is getting a bit long in the tooth and may require a revision in the future to fix this. Thanks for pointing it out!

**Comment by mjsteinbaugh** [comment]
Briefly, you're seeing this issue:

```
plotDEGHeatmap(results = res, counts = vst)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘plotDEGHeatmap’ for signature ‘"missing"’
```

Because the `plotDEGHeatmap` generic function dispatches on `object` instead of `results` as the primary argument. Generics in R can be a bit cryptic about this mismatch error in R, and should say use "object" instead of "results" instead of returning `signature ‘"missing"’`. But I also recommend that you create a `DESeqAnalysis` object as explained in the post and the updated bcbioRNASeq differential expression workflow, which makes usage of such visualization functions like `plotDEGHeatmap` a bit more intuitive.
