### ISSUE TITLE
Genes with 0 counts are kept

### ISSUE THREAD

**Issue by vbarrera** [hbc/bcbioRNASeq#4]
When loading the results from bcbio no filtering for 0 counts genes is done previous to any other step of the analysis. This results in weird meanSdPlots (for example). Thanks to @lpantano finding the origin of the problem.

**Comment by mjsteinbaugh** [comment]
There's a few ways to handle this in our scripts:

1. Store non-zero counts in a slot in the `bcbioRnaDataSet`. I'm not partial to this approach because it will make the object unnecessarily large and essentially duplicate the count data.
2. Write a function for the `meanSdPlots()` that pre-filters the zero counts.
3. Add a zero count filtering step into our RMarkdown template.

I'm thinking option 2 may be the best because it will be easier to document?

**Comment by mjsteinbaugh** [comment]
Issue has been fixed in recent update
