### ISSUE TITLE
plot_correlation_heatmap, select not found

### ISSUE THREAD

**Issue by vbarrera** [hbc/bcbioRNASeq#5]
When used, an error appears 
 **Error in select(., !(!quo(intgroup))): could not find function "select"**
Solved by loading dplyr. Needs to be added to the libraries to load.

**Comment by mjsteinbaugh** [comment]
Loading dplyr doesn't solve the issue. We should only require `library(bcbioRnaseq)` project-wide in the setup chunk. Analysis-specific libraries can then be loaded on demand, such as `library(DESeq2)`. There are NAMESPACE collisions between many Bioconductor generics (see Biobase, BiocGenerics, S4Vectors documentation) and the tidyverse (see dplyr, tidyr documentation). What we need to do is handle the NAMESPACE conflicts inside the package rather than opting to load libraries in the workflows. Otherwise, you'll end up with unexpected NAMESPACE problems, usually with `arrange()`, `filter()`, or `select()`. We should opt to import these generics in functions that utilize tidyverse operations. I wrote a wrapper called `import_tidy_verbs()` that handles this inside the package, but there may be a better approach.

**Comment by mjsteinbaugh** [comment]
Here's a running list of common NAMESPACE collisions with Bioconductor generics, which we need to keep in mind when writing functions that operate on S4s:
https://github.com/steinbaugh/basejump/blob/master/R/tidyverse.R

**Comment by mjsteinbaugh** [comment]
Alternatively, maybe we can instead define them as generics (see example):
https://github.com/davismcc/scater/blob/master/R/AllGenerics.R

**Comment by mjsteinbaugh** [comment]
We've decided to use `AnnotationDbi::select()` as the default verb and resort to remapping `dplyr::select()` to `tidy_select()`. This should be fixed in the recent package updates.
