### ISSUE TITLE
Error: GRCh37/hg19 detected. 'annotable' argument must be set to 'annotables::grch37'.

### ISSUE THREAD

**Issue by hliu2016** [hbc/bcbioRNASeq#59]
This looks like wonderful work.
I test the loadRNASeq() function by using the command
`loadRNASeq(uploadDir = "final")`
However,  I got the error as:

> 2017-12-02_seqc
> 6 samples detected
> Reading project-summary.yaml
> Genome: Homo sapiens (GRCh37)
> Error: GRCh37/hg19 detected. 'annotable' argument must be set to 'annotables::grch37'.
> In addition: There were 14 warnings (use warnings() to see them)

So, I set the annotable parameter to "annotables::grch37" in the command
`bcb = loadRNASeq(uploadDir = "final",annotable = "annotables::grch37")`
Unfortunately, error occured again. The output is as below:

> 2017-12-02_seqc
> 6 samples detected
> Reading project-summary.yaml
> Genome: Homo sapiens (GRCh37)
> Parsed with column specification:
> cols(
> .........
> summarizing abundance
> summarizing counts
> summarizing length
> Generating internal DESeqDataSet for quality control
> using just counts from tximport
> estimating size factors
> estimating dispersions
> gene-wise dispersion estimates
> mean-dispersion relationship
> final dispersion estimates
> fitting model and testing
> Performing rlog transformation
> Performing variance stabilizing transformation
> Reading STAR featureCounts aligned counts
> Parsed with column specification:
> cols(
>   id = col_character(),
>   HBRR_rep1 = col_integer(),
>   HBRR_rep2 = col_integer(),
>   HBRR_rep3 = col_integer(),
>   UHRR_rep1 = col_integer(),
>   UHRR_rep2 = col_integer(),
>   UHRR_rep3 = col_integer()
> )
> **Error: rowData must support 'dim()'**

How can I tackle this problem? Thanks a lot.

**Comment by mjsteinbaugh** [comment]
@hliu2016 Thanks, I need to make this warning more informative when bcbio is run using the [GRCh37/hg19 genome build](http://grch37.ensembl.org/index.html). I'll add native GRCh37 support in the next version of the package.

The issue is that GRCh37 is no longer well supported in the current recommend Bioconductor methods for accessing Ensembl annotations. We have switched from using [biomaRt](https://bioconductor.org/packages/release/bioc/html/biomaRt.html) to [ensembldb](https://bioconductor.org/packages/release/bioc/html/ensembldb.html), which doesn't support GRCh37 genome annotations. To account for this, we've been recommending the [annotables](https://github.com/stephenturner/annotables) package, which has a prebuilt Ensembl annotation tibble for GRCh37.

In the meantime, you should be able to get the data loaded up by installing the annotables package, and then passing the `annotables::grch37` tibble into our `loadRNASeq()` function using the `annotable` argument.

**Comment by hliu2016** [comment]
@mjsteinbaugh Thanks for your kind reply. Following your suggestions, I installed the annotable package by using 
`source("https://bioconductor.org/biocLite.R")`
`biocLite("stephenturner/annotables")`

The package is successfully installed, and then I retried the loadRNASeq() function by passing the annotable argument:
`bcb = loadRNASeq(uploadDir = "final",annotable = "annotables::grch37")`

However,  the same error occured and the loadRNASeq() function failed.

> Error: rowData must support 'dim()'

**Comment by lpantano** [comment]
I think you should do:

bcb = loadRNASeq(uploadDir = "final",annotable = annotables::grch37)

Without quotations. But I never tried.

**Comment by hliu2016** [comment]
@lpantano 
Thank you very much. It works!

**Comment by hliu2016** [comment]
@mjsteinbaugh @lpantano 

I have passed all function before running the plotVolcano().  The error information is below:

`>plotVolcano(res)`

> Loading Ensembl annotations from AnnotationHub
> 2017-10-27
> Error: failed to load resource
>   name: AH57757
>   title: Ensembl 90 EnsDb for Homo Sapiens
>   reason: Could not connect to database:
> unable to open database file

How can I work out this problem? Thanks in advance.

**Comment by mjsteinbaugh** [comment]
That's a feature I've been working on to improve and it's updated in version 0.1.3 of the package. Check our online documentation for [plotVolcano()](http://bioinformatics.sph.harvard.edu/bcbioRNASeq/reference/plotVolcano.html).

Since we're working with a DESeqResults object here (`res`), we have to include Ensembl gene-to-symbol annotations if we want to label genes on the plot. The easiest way to manage this is to have the function get the annotations automatically from Ensembl, but it doesn't work well for the GRCh37/hg19 genome build, since it's archived.

If you just want to plot the volcano, you can set `gene2symbol = FALSE` here. Or, you can access the gene2symbol mappings saved in your bcbioRNASeq using `gene2symbol(bcb)`, and pass that resulting data.frame into `plotVolcano()` using the `gene2symbol` parameter. Let me know if that works.

**Comment by hliu2016** [comment]
@mjsteinbaugh 

Thank you very much. Can I update the bcbioRNASeq package to 0.1.3 now? I have tried the gene2symbol function, error occured as follows:
`>gene2symbol <- gene2symbol(bcb)` 

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function 'gene2symbol' for signature '"bcbioRNASeq"'

**Comment by hliu2016** [comment]
@mjsteinbaugh 
Thanks very much. It works!
This is a really nice work. I'd like to explore it in depth.
