### ISSUE TITLE
How to display the gene symbols on the volcano plot in the differential expression template?

### ISSUE THREAD

**Issue by hliu2016** [hbc/bcbioRNASeq#99]
Hi, I have successfully run the differential expression rmarkdown template. It worked quite well. But I found that the volcano plot for the differentially expressed genes does not display the gene symbols. Is there any method to do this?

**Comment by mjsteinbaugh** [comment]
Indeed there is! Check out the documentation here:
http://bioinformatics.sph.harvard.edu/bcbioRNASeq/reference/plotVolcano.html

You can label specific genes with the `genes` argument or label the top genes automatically using the `ntop` argument. Note that for the `genes` argument, we're requiring the Ensembl gene IDs instead of the gene symbols, which is better for code reproducibility.

The `DESeqDataSet` needs to be created using `as(bcb, "DESeqDataSet")` in order to contain the gene symbols. This information is saved in `rowRanges()` (`GRanges` object; see also `mcols()` function for working with `GRanges` metadata). The gene-to-symbol mappings are also accessible with the `rowData()` function and will return a `DataFrame`. These are mapped between the `geneID` and `geneName` (symbol) columns. Those are the values that will be used automatically in the volcano and MA plots.

**Comment by hliu2016** [comment]
Thanks very much. The `ntop` parameter works well.
